In [4]:
import pandas as pd
import numpy as np
data=pd.read_csv('/home/ashmin/Documents/Python/3D_Reconstruction/datasets/fountain-P11/calibration.csv')
data.head()

6                          camera_intrinsics
0  a  2759.48 0 1520.69 0 2764.16 1006.81 0 0 1
1  b  2759.48 0 1520.69 0 2764.16 1006.81 0 0 1
2  c  2759.48 0 1520.69 0 2764.16 1006.81 0 0 1
3  d  2759.48 0 1520.69 0 2764.16 1006.81 0 0 1
4  e  2759.48 0 1520.69 0 2764.16 1006.81 0 0 1

In [3]:
df=pd.DataFrame(data)
value=1
print(df.columns.values.tolist())
df_1=df.loc[df['image_id']==value,'camera_intrinsics']
print(df_1)


['image_id', 'camera_intrinsics']
0    2759.48 0 1520.69 0 2764.16 1006.81 0 0 1
Name: camera_intrinsics, dtype: object


In [1]:
class ClassA:
    def __init__(self) -> None:
        self.a = 1
    
    def inc(self):
        self.a += 1

In [2]:
class ClassB:
    def __init__(self, x) -> None:
        self.x_obj = x
    
    def inc(self):
        self.x_obj.a += 1

In [3]:
s = ClassA()

In [4]:
d = ClassB(s)

In [12]:
s.a

3

In [6]:
s.inc()

In [11]:
d.x_obj.a

3

In [10]:
d.inc()

In [19]:
from pympler import asizeof
asizeof.asizeof(s)

240

In [13]:
import sys

In [17]:
sys.getsizeof(s.inc)

64

In [42]:
class Point:
  
    # defining the coordinate variables
    def __init__(self):
        self.x = 1
        self.y = 2
        self.z = 3
  
Coordinates = Point()
print(sys.getsizeof(Coordinates))
asizeof.asizeof(Coordinates), asizeof.asizeof(Coordinates.x)

48


(328, 32)

In [37]:
asizeof.asizeof(Coordinates)

416

In [1]:
w=None

In [2]:
w is None

True

In [2]:
print("findHomography(srcPoints, dstPoints[, method[, ransacReprojThreshold[, mask[, maxIters[, confidence]]]]]) -> retval, mask\n.   @brief Finds a perspective transformation between two planes.\n.   \n.   @param srcPoints Coordinates of the points in the original plane, a matrix of the type CV_32FC2\n.   or vector\\<Point2f\\> .\n.   @param dstPoints Coordinates of the points in the target plane, a matrix of the type CV_32FC2 or\n.   a vector\\<Point2f\\> .\n.   @param method Method used to compute a homography matrix. The following methods are possible:\n.   -   **0** - a regular method using all the points, i.e., the least squares method\n.   -   **RANSAC** - RANSAC-based robust method\n.   -   **LMEDS** - Least-Median robust method\n.   -   **RHO** - PROSAC-based robust method\n.   @param ransacReprojThreshold Maximum allowed reprojection error to treat a point pair as an inlier\n.   (used in the RANSAC and RHO methods only). That is, if\n.   \\f[\\| \\texttt{dstPoints} _i -  \\texttt{convertPointsHomogeneous} ( \\texttt{H} * \\texttt{srcPoints} _i) \\|_2  >  \\texttt{ransacReprojThreshold}\\f]\n.   then the point \\f$i\\f$ is considered as an outlier. If srcPoints and dstPoints are measured in pixels,\n.   it usually makes sense to set this parameter somewhere in the range of 1 to 10.\n.   @param mask Optional output mask set by a robust method ( RANSAC or LMEDS ). Note that the input\n.   mask values are ignored.\n.   @param maxIters The maximum number of RANSAC iterations.\n.   @param confidence Confidence level, between 0 and 1.\n.   \n.   The function finds and returns the perspective transformation \\f$H\\f$ between the source and the\n.   destination planes:\n.   \n.   \\f[s_i  \\vecthree{x'_i}{y'_i}{1} \\sim H  \\vecthree{x_i}{y_i}{1}\\f]\n.   \n.   so that the back-projection error\n.   \n.   \\f[\\sum _i \\left ( x'_i- \\frac{h_{11} x_i + h_{12} y_i + h_{13}}{h_{31} x_i + h_{32} y_i + h_{33}} \\right )^2+ \\left ( y'_i- \\frac{h_{21} x_i + h_{22} y_i + h_{23}}{h_{31} x_i + h_{32} y_i + h_{33}} \\right )^2\\f]\n.   \n.   is minimized. If the parameter method is set to the default value 0, the function uses all the point\n.   pairs to compute an initial homography estimate with a simple least-squares scheme.\n.   \n.   However, if not all of the point pairs ( \\f$srcPoints_i\\f$, \\f$dstPoints_i\\f$ ) fit the rigid perspective\n.   transformation (that is, there are some outliers), this initial estimate will be poor. In this case,\n.   you can use one of the three robust methods. The methods RANSAC, LMeDS and RHO try many different\n.   random subsets of the corresponding point pairs (of four pairs each, collinear pairs are discarded), estimate the homography matrix\n.   using this subset and a simple least-squares algorithm, and then compute the quality/goodness of the\n.   computed homography (which is the number of inliers for RANSAC or the least median re-projection error for\n.   LMeDS). The best subset is then used to produce the initial estimate of the homography matrix and\n.   the mask of inliers/outliers.\n.   \n.   Regardless of the method, robust or not, the computed homography matrix is refined further (using\n.   inliers only in case of a robust method) with the Levenberg-Marquardt method to reduce the\n.   re-projection error even more.\n.   \n.   The methods RANSAC and RHO can handle practically any ratio of outliers but need a threshold to\n.   distinguish inliers from outliers. The method LMeDS does not need any threshold but it works\n.   correctly only when there are more than 50% of inliers. Finally, if there are no outliers and the\n.   noise is rather small, use the default method (method=0).\n.   \n.   The function is used to find initial intrinsic and extrinsic matrices. Homography matrix is\n.   determined up to a scale. Thus, it is normalized so that \\f$h_{33}=1\\f$. Note that whenever an \\f$H\\f$ matrix\n.   cannot be estimated, an empty one will be returned.\n.   \n.   @sa\n.   getAffineTransform, estimateAffine2D, estimateAffinePartial2D, getPerspectiveTransform, warpPerspective,\n.   perspectiveTransform")

findHomography(srcPoints, dstPoints[, method[, ransacReprojThreshold[, mask[, maxIters[, confidence]]]]]) -> retval, mask
.   @brief Finds a perspective transformation between two planes.
.   
.   @param srcPoints Coordinates of the points in the original plane, a matrix of the type CV_32FC2
.   or vector\<Point2f\> .
.   @param dstPoints Coordinates of the points in the target plane, a matrix of the type CV_32FC2 or
.   a vector\<Point2f\> .
.   @param method Method used to compute a homography matrix. The following methods are possible:
.   -   **0** - a regular method using all the points, i.e., the least squares method
.   -   **RANSAC** - RANSAC-based robust method
.   -   **LMEDS** - Least-Median robust method
.   -   **RHO** - PROSAC-based robust method
.   @param ransacReprojThreshold Maximum allowed reprojection error to treat a point pair as an inlier
.   (used in the RANSAC and RHO methods only). That is, if
.   \f[\| \texttt{dstPoints} _i -  \texttt{convertPointsHomogeneous

In [4]:
import numpy as np
f= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
f

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
f.transpose(-2,-1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
import torch

In [32]:
x = torch.randn(3,3)
x

tensor([[ 0.4847, -0.4098, -0.5676],
        [ 1.1815, -1.0843,  0.6238],
        [-0.6620, -1.0690, -0.0148]])

In [33]:
xt = x.transpose(-2,-1)

In [34]:
_, s, vh = torch.svd(xt)
e = vh[..., -1]
e

tensor([-0.9651,  0.2609,  0.0243])